version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "find-discounts-app"
s3_bucket = "find-discounts-app-bucket"
s3_prefix = "find-discounts-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
