Parameters:
  Stage:
    Type: String
    Default: dev

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  createUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-crud/
      Handler: handler.createUser
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref userTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt userTable.Arn
      Events:
        CreateUser:
          Type: Api
          Properties:
            # Auth: authorizer
            Path: /user-register
            Method: post
            RestApiId: !Ref ApiDeployment

  # User dynamodb table
  userTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["", ["user-", Ref: Stage]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
